#server:
#  port: 9001
  #设置服务名
spring:
  application:
    name: see-time
  zipkin:
    #指定zipkin服务端的url
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #设定样本收集的比率为100%
      percentage: 1.0

#设置服务注册中心的URL，本服务要向该服务注册中心注册自己
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

