server:
  port: 1112

spring:
  application:
    name: eureka-service
  #设定主机名为peer1
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka

  #eureka.client.register-with-eureka=false
  #eureka.client.fetch-registry=false
  #设定eureka的serviceUrl为peer2
